// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SESSION_SECRET: "change-this-in-production";
	BETTER_AUTH_URL: "https://the-language-dojo.pages.dev";
	BETTER_AUTH_SECRET: string;
	DB: D1Database;
}
